create table if not exists public.petko_scores (
  id bigint generated by default as identity primary key,
  play_date date not null,
  device_id text not null,
  player_name text not null default 'Igrac',
  status text not null check (status in ('finished', 'failed')),
  started integer not null default 0,
  total_score integer not null default 0,
  score_difference integer not null default 0,
  final_score numeric not null default 0,
  completed integer not null default 0,
  level integer not null default 0,
  words text not null default '',
  points text not null default '',
  attempts integer not null default 0,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (play_date, device_id)
);

alter table public.petko_scores enable row level security;

drop policy if exists "petko_scores_read" on public.petko_scores;
create policy "petko_scores_read"
on public.petko_scores
for select
to anon
using (true);

drop policy if exists "petko_scores_insert" on public.petko_scores;
create policy "petko_scores_insert"
on public.petko_scores
for insert
to anon
with check (true);

drop policy if exists "petko_scores_update" on public.petko_scores;
create policy "petko_scores_update"
on public.petko_scores
for update
to anon
using (true)
with check (true);
