create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  nickname text not null,
  score integer not null default 0,
  attempts integer not null default 0,
  wins integer not null default 0,
  streak integer not null default 0
);

alter table public.scores enable row level security;

drop policy if exists "scores_read" on public.scores;
create policy "scores_read"
on public.scores
for select
to anon
using (true);

drop policy if exists "scores_insert" on public.scores;
create policy "scores_insert"
on public.scores
for insert
to anon
with check (true);
