create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  nickname text not null,
  score integer not null default 0, -- daily score
  attempts integer not null default 0,
  wins integer not null default 0,
  streak integer not null default 0
);

alter table public.scores enable row level security;

drop policy if exists "scores_read" on public.scores;
create policy "scores_read"
on public.scores
for select
to anon
using (true);

drop policy if exists "scores_insert" on public.scores;
create policy "scores_insert"
on public.scores
for insert
to anon
with check (true);

create table if not exists public.players (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  last_seen timestamptz not null default now(),
  nickname text not null,
  device_id text,
  avatar_id text
);

create unique index if not exists players_nickname_unique
on public.players (lower(btrim(nickname)));

alter table public.players
add column if not exists avatar_id text;

alter table public.players enable row level security;

drop policy if exists "players_read" on public.players;
create policy "players_read"
on public.players
for select
to anon
using (true);

drop policy if exists "players_insert" on public.players;
create policy "players_insert"
on public.players
for insert
to anon
with check (true);

drop policy if exists "players_update" on public.players;
create policy "players_update"
on public.players
for update
to anon
using (true)
with check (true);

create table if not exists public.challenges (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  accepted_at timestamptz,
  code text not null unique,
  day date not null default current_date,
  creator text not null,
  creator_device text,
  opponent text,
  opponent_device text,
  status text not null default 'pending',
  words jsonb not null,
  creator_score integer,
  creator_attempts integer,
  creator_solved integer,
  creator_played_at timestamptz,
  opponent_score integer,
  opponent_attempts integer,
  opponent_solved integer,
  opponent_played_at timestamptz
);

alter table public.challenges enable row level security;

drop policy if exists "challenges_read" on public.challenges;
create policy "challenges_read"
on public.challenges
for select
to anon
using (true);

drop policy if exists "challenges_insert" on public.challenges;
create policy "challenges_insert"
on public.challenges
for insert
to anon
with check (true);

drop policy if exists "challenges_update" on public.challenges;
create policy "challenges_update"
on public.challenges
for update
to anon
using (true)
with check (true);

drop policy if exists "challenges_delete" on public.challenges;
create policy "challenges_delete"
on public.challenges
for delete
to anon
using (true);

create or replace function public.enforce_challenge_daily_limits()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.creator_device is not null
    and new.opponent is not null
    and btrim(new.opponent) <> ''
    and lower(btrim(new.opponent)) not in (lower('Нови корисник'), lower('Чека се'))
    and (
    select count(*)
    from public.challenges
    where creator_device = new.creator_device
      and day = new.day
      and opponent is not null
      and btrim(opponent) <> ''
      and lower(btrim(opponent)) not in (lower('Нови корисник'), lower('Чека се'))
      and status <> 'cancelled'
      and (
        status <> 'pending'
        or created_at > now() - interval '6 hours'
      )
  ) >= 9 then
    raise exception 'daily challenge limit reached';
  end if;
  return new;
end;
$$;
drop trigger if exists challenges_daily_limit_trigger on public.challenges;
create trigger challenges_daily_limit_trigger
before insert on public.challenges
for each row execute function public.enforce_challenge_daily_limits();

create table if not exists public.normal_stats (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  nickname text not null,
  device_id text not null unique,
  started integer not null default 0,
  finished integer not null default 0
);

alter table public.normal_stats enable row level security;

drop policy if exists "normal_stats_read" on public.normal_stats;
create policy "normal_stats_read"
on public.normal_stats
for select
to anon
using (true);

drop policy if exists "normal_stats_insert" on public.normal_stats;
create policy "normal_stats_insert"
on public.normal_stats
for insert
to anon
with check (true);

drop policy if exists "normal_stats_update" on public.normal_stats;
create policy "normal_stats_update"
on public.normal_stats
for update
to anon
using (true)
with check (true);

create table if not exists public.word_reports (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  word text not null,
  action text not null,
  source text not null,
  nickname text,
  device_id text
);

alter table public.word_reports enable row level security;

drop policy if exists "word_reports_read" on public.word_reports;
create policy "word_reports_read"
on public.word_reports
for select
to anon
using (true);

drop policy if exists "word_reports_insert" on public.word_reports;
create policy "word_reports_insert"
on public.word_reports
for insert
to anon
with check (true);

create table if not exists public.word_meanings (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  word text not null unique,
  meaning text not null,
  note text
);

alter table public.word_meanings enable row level security;

drop policy if exists "word_meanings_read" on public.word_meanings;
create policy "word_meanings_read"
on public.word_meanings
for select
to anon
using (true);

insert into public.players (nickname)
select candidate.nickname
from (
  select btrim(nickname) as nickname from public.scores
  union
  select btrim(nickname) as nickname from public.normal_stats
  union
  select btrim(creator) as nickname from public.challenges
  union
  select btrim(opponent) as nickname from public.challenges
) as candidate
where candidate.nickname is not null
  and candidate.nickname <> ''
  and lower(candidate.nickname) <> lower('Чека се')
  and not exists (
    select 1
    from public.players existing
    where lower(btrim(existing.nickname)) = lower(candidate.nickname)
  );

