-- Petko: cloud mid-game sessions for multi-device continue.
-- Run once in THIS project's Supabase SQL Editor (https://kfpyrajlxrucmrlhyvgr.supabase.co).
-- Safe to re-run.

create table if not exists public.game_sessions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  nickname text not null,
  nickname_key text not null,
  profile_device_id text,
  device_id text,
  mode text not null check (mode in ('competitive', 'normal', 'challenge')),
  challenge_code text not null default '',
  day date,
  status text not null default 'in_progress',
  payload jsonb not null default '{}'::jsonb
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'game_sessions_player_mode_key'
  ) then
    alter table public.game_sessions
      add constraint game_sessions_player_mode_key
      unique (nickname_key, mode, challenge_code);
  end if;
end $$;

create index if not exists game_sessions_nickname_key_idx
  on public.game_sessions (nickname_key, updated_at desc);

create index if not exists game_sessions_profile_device_idx
  on public.game_sessions (profile_device_id, updated_at desc);

create or replace function public.touch_game_session_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  new.nickname_key = lower(btrim(coalesce(new.nickname, '')));
  new.challenge_code = upper(btrim(coalesce(new.challenge_code, '')));
  return new;
end;
$$;

drop trigger if exists game_sessions_touch_updated_at on public.game_sessions;
create trigger game_sessions_touch_updated_at
before insert or update on public.game_sessions
for each row execute function public.touch_game_session_updated_at();

alter table public.game_sessions enable row level security;

drop policy if exists "game_sessions_read" on public.game_sessions;
create policy "game_sessions_read"
on public.game_sessions
for select
to anon
using (true);

drop policy if exists "game_sessions_insert" on public.game_sessions;
create policy "game_sessions_insert"
on public.game_sessions
for insert
to anon
with check (true);

drop policy if exists "game_sessions_update" on public.game_sessions;
create policy "game_sessions_update"
on public.game_sessions
for update
to anon
using (true)
with check (true);

drop policy if exists "game_sessions_delete" on public.game_sessions;
create policy "game_sessions_delete"
on public.game_sessions
for delete
to anon
using (true);

comment on table public.game_sessions is
  'In-progress Classic / Competitive / Challenge runs so a player can continue on another device.';
